### ISSUE TITLE
Hot-keys and Categories for menu objects

### ISSUE THREAD

**Issue by cousincuey** [RITAccess/blockly#1]

**Comment by rkbosley** [comment]
Currently waiting for interface to be mostly finalized before finishing. You need to be able to access the menu via hotkey which is a problem right now. A key will open menu, 1-0 will choose category, A-Z will choose block.

**Comment by amber-libby** [comment]
Repeat Issue... instead refer to the issue "Adding shortcuts to access menu (1a - 4c etc.)"
