### ISSUE TITLE
Adding shortcuts to access menu (1a - 4c etc.) 

### ISSUE THREAD

**Issue by MaryS94** [RITAccess/blockly#14]
Up and down arrows can currently be used to traverse through the menu but we would like to add a way to quickly jump to each category and block

**Comment by rkbosley** [comment]
Current plan for adding a block: Press A key. This should allow you to tab through menu categories in addition to enabling number keys for category selection. When you select a category, all other categories are no longer accessible. Escape key can go back to category selection. Blocks can now be added to the scene using Tab + Enter or by hitting the relevant letter (a is the first block, b is the second block, and so on). When a block is added to the scene, the menu is automatically exited.

**Comment by MaryS94** [comment]
1-9 can be used to quickly jump to categories however, using letters to quickly choose a block would likely be more confusing than helpful to the user.
