### ISSUE TITLE
Buttons give warnings when used (EXCLUDES import/export XML buttons)

### ISSUE THREAD

**Issue by amber-libby** [RITAccess/blockly#15]
In interface make a block program and click the run javascript button and a caution appears in the javascript console saying "No workspace specified in workspaceToCode call.  Guessing." from line 74 of generator.js.

**Comment by amber-libby** [comment]
To Javascript, To Python, To Dart, and Run Javascript buttons give warning messages when pressed.

**Comment by MaryS94** [comment]
After the update the buttons no longer throw warnings
