### ISSUE TITLE
Mutator icon on blocks needs to be accessible (currently drag and drop)

### ISSUE THREAD

**Issue by amber-libby** [RITAccess/blockly#23]
The blocks with the gear icon have mutators which are currently drag and drop. The blocks with mutators are: if, create text with, create list with, function with return, and function no return.

**Comment by amber-libby** [comment]
A solution could be to put each possible mutation block in another category in the toolbox menu. Then the block could be added similarly to the connections are. Another idea was to have a mutation hotkey mode inside of the edit mode. None of this has been started.

**Comment by MaryS94** [comment]
- If, else if, and else now have their own blocks.
- Create text with and create list with use a text field to input how many items the user wants to combine.
- Function blocks also use a text field to determine how many parameters are being used.
