### ISSUE TITLE
Connecting Blocks

### ISSUE THREAD

**Issue by MaryS94** [RITAccess/blockly#3]
Blocks currently cannot be connected via keyboard.
We need to figure out how to connect them as they are made as well as inserting them later.

**Comment by amber-libby** [comment]
Example to keep in mind: Need to be able to connect a block that is intended to be a value such as the number block and connect it backwards to a block it is compatible with.

**Comment by amber-libby** [comment]
Now able to add blocks to the screen and connect them using keystrokes. Still a bit buggy but will make issues as they arise.
