### ISSUE TITLE
Change how navigating blocks with multiple inputs is selected 

### ISSUE THREAD

**Issue by MaryS94** [RITAccess/blockly#38]
This refers to blocks such as 'create text with' and 'create list with'

**Comment by MaryS94** [comment]
F can now be used to navigate through inputs

**Comment by acaraballo003** [comment]
Tested this on my computer 
Used an if block with an if, do and a bottom connection.
the if connection had 2 children
the do connection was an else if with another if connection and a do
and the bottom connection was an else

f only looped through the three connections most of the time
sometimes went into the do connection and it's in line connection

**Comment by acaraballo003** [comment]
F now navigates strictly inline

**Comment by MaryS94** [comment]
Awesome! Can you push that to the repo? Also be sure to make a copy just in case the sync goes wrong.

**Comment by MaryS94** [comment]
I'm glad you figured out how to stop it from jumping to the block below but it looks like it can only access the first inner block. For instance in: `if A = B `  you can only get to the A not the B . I know that B isn't _technically_ the inline of A but it would make sense for reading aloud the if statement as the user presses F to try and find where to edit B. The screen reader should end up sounding something like this as they navigate through: "if A = B" > "A = B" > "A" >"B" > "A"(looping through the last inputs unless we create a way to go backwards)

**Comment by MaryS94** [comment]
I just found several useful functions in core/block.js that I can't believe I didn't know existed. (getSurroundParent, getDescendants, getChildren etc) and Im pretty sure I can fix it using those but I have class soon so don't worry about fixing it for now since I'll mess around with it later.

**Comment by acaraballo003** [comment]
Does it error when the user tries to access B with the F key?

Because I haven't quite handled that yet, I just changed what was in the
else statement so the children could be accessed. I tested it on one of the
loop blocks with 3 slots open (count with I from _ to _ by _) and the F key
looped through them fine.
So do you think it's something in the final else statement?

-Ari

**Comment by acaraballo003** [comment]
It should work now... I had tried making the code more readable  by creating a var and apparently that was causing issues. Let me know if it still does not work on your computer

**Comment by MaryS94** [comment]
Awesome it works now!
