### ISSUE TITLE
inputsInline: undefined

### ISSUE THREAD

**Issue by acaraballo003** [RITAccess/blockly#45]
Is this supposed to be an array? If so, could we try adding inline blocks to this array instead of having them all in childBlocks_ in order to make the F keyboard nav more simple?

**Comment by MaryS94** [comment]
inputsInline is a boolean that refers to when you right click a block and choose the option to display the inputs inline. childBlocks_ is what blockly uses to store each blocks children so we can't really change where the blocks are with that. Our best bet is probably finding another attribute that distinguishes the two types of inputs, maybe the connection type?
