### ISSUE TITLE
Labeling What Level/ Where you currently are in the code

### ISSUE THREAD

**Issue by MaryS94** [RITAccess/blockly#5]
Using a letter/ number system to label where you are and being able to quickly jump to that location.

**Comment by amber-libby** [comment]
There is a function called commentPrefix() in commentGenerator.js which generates all of the labels for the code navigation. It returns an array of the prefixes in the order corresponding to the code.

**Comment by cousincuey** [comment]
Our function now generates prefixes for the outer blocks as well as handling all the inner blocks and names them in an understandable order.

**Comment by amber-libby** [comment]
Refer to General Project notes for the breakdown of how labeling works.
