### ISSUE TITLE
Changing Right Click Navigation

### ISSUE THREAD

**Issue by MaryS94** [RITAccess/blockly#6]
There are a lot of functions that can only be used by right clicking that need to be changed.

**Comment by rkbosley** [comment]
We can enable the menu, but we need to decide if we want to. This essentially a non-issue at this point due to hotkeys. This should be a minor change after everything else has been completed.

**Comment by amber-libby** [comment]
We have keystrokes to complete all the functionality in the right-click dropdown menu.
